name: Build and deploy
on:
  schedule:
    - cron: '1 1 */10 * *'
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: yarn install

      - run: yarn build:pp

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          # see https://github.com/peaceiris/actions-gh-pages#1-add-ssh-deploy-key
          # ssh-keygen -t rsa -b 4096 -C "$(git config user.email)" -f gh-pages -N ""
          # Upload your public key (gh-pages.pub) to your the projects settings => deploy keys
          # Upload the private key (gh-pages) to github action secrets
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
